#!/usr/bin/env node
// Builds the installable web version into dist-web/.
//
// Same renderer sources as the desktop app; only three things change:
//   - index.html loses the Electron-only preload assumption and gets a CSP that permits the
//     four API hosts, since the page now calls them itself instead of going through IPC
//   - a service worker precaches every asset so the app opens with no connection
//   - a manifest + icons make it installable from Chrome's "Add to Home screen"

const fs = require('node:fs');
const path = require('node:path');

const ROOT = __dirname;
const OUT = path.join(ROOT, 'dist-web');
const R = path.join(ROOT, 'src', 'renderer');

const API_HOSTS = [
  'https://api.dictionaryapi.dev',
  'https://en.wiktionary.org',
  'https://api.mymemory.translated.net',
  'https://api.datamuse.com',
  'https://api.languagetool.org',
].join(' ');

const copy = (from, to) => {
  fs.mkdirSync(path.dirname(to), { recursive: true });
  fs.copyFileSync(from, to);
};

function walk(dir, base = dir, acc = []) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p, base, acc);
    else acc.push(path.relative(base, p).split(path.sep).join('/'));
  }
  return acc;
}

fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(OUT, { recursive: true });

// --- renderer sources ---
for (const rel of walk(R)) copy(path.join(R, rel), path.join(OUT, rel));
copy(path.join(ROOT, 'src', 'shared', 'net.js'), path.join(OUT, 'shared/net.js'));

// --- index.html: CSP + manifest + service worker registration ---
let html = fs.readFileSync(path.join(R, 'index.html'), 'utf8');
html = html.replace(
  /<meta http-equiv="Content-Security-Policy"[^>]*>/,
  `<meta http-equiv="Content-Security-Policy" content="default-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; media-src 'self' blob: https:; connect-src 'self' ${API_HOSTS}" />`,
);
html = html.replace('<script src="../shared/net.js"></script>', '<script src="shared/net.js"></script>');
html = html.replace(
  '</head>',
  `  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
  <meta name="theme-color" content="#17325c" />
  <link rel="manifest" href="manifest.webmanifest" />
  <link rel="icon" href="icon-192.png" />
  <link rel="apple-touch-icon" href="icon-192.png" />
  <link rel="stylesheet" href="mobile.css" />
</head>`,
);
// An external file, not an inline <script>: the CSP forbids inline execution and relaxing it
// just to register the worker would weaken every page in the app.
html = html.replace('</body>', '  <script src="sw-register.js"></script>\n</body>');
fs.writeFileSync(path.join(OUT, 'index.html'), html);
fs.writeFileSync(
  path.join(OUT, 'sw-register.js'),
  `if ('serviceWorker' in navigator) {
  // The worker serves cached assets first, so a page opened while an update is installing still
  // shows the old build. Reload once when the new worker takes over, so a refresh is enough to
  // pick up a new version instead of needing the app closed and reopened twice.
  let reloading = false;
  navigator.serviceWorker.addEventListener('controllerchange', () => {
    if (reloading) return;
    reloading = true;
    location.reload();
  });
  window.addEventListener('load', () => {
    navigator.serviceWorker.register('sw.js').catch((e) => console.warn('service worker:', e.message));
  });
}
`,
);

// --- manifest ---
fs.writeFileSync(
  path.join(OUT, 'manifest.webmanifest'),
  JSON.stringify(
    {
      name: 'LingoTask',
      short_name: 'LingoTask',
      description: 'IELTS 6.5 çalışma uygulaması',
      start_url: './index.html',
      scope: './',
      display: 'standalone',
      orientation: 'portrait',
      background_color: '#f3f5f9',
      theme_color: '#17325c',
      lang: 'tr',
      icons: [192, 512].map((s) => ({ src: `icon-${s}.png`, sizes: `${s}x${s}`, type: 'image/png', purpose: 'any maskable' })),
    },
    null,
    2,
  ),
);

// --- icons (generated by build-icons.js into build/) ---
for (const s of [192, 512]) {
  const src = path.join(ROOT, 'build', `icon-${s}.png`);
  if (fs.existsSync(src)) copy(src, path.join(OUT, `icon-${s}.png`));
  else console.warn(`! build/icon-${s}.png missing — run "npm run icons" first`);
}

// --- service worker: precache everything, network-first for the APIs ---
const assets = walk(OUT).filter((f) => f !== 'sw.js');
const version = Date.now();
fs.writeFileSync(
  path.join(OUT, 'sw.js'),
  `// Generated by build-web.js — do not edit.
// Precaches the whole app so it opens offline; API calls stay network-first because the
// renderer keeps its own semantic cache of lookups in saved state.
const CACHE = 'lingotask-v${version}';
const ASSETS = ${JSON.stringify(['./', ...assets], null, 2)};

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (e) => {
  const url = new URL(e.request.url);
  if (url.origin !== location.origin) return; // API calls: let them fail normally so the app can fall back
  e.respondWith(
    caches.match(e.request, { ignoreSearch: true }).then((hit) => hit || fetch(e.request)),
  );
});
`,
);

console.log(`dist-web/ built — ${assets.length + 1} files`);
